model = "gpt-6.1-sol"
model_reasoning_effort = "high"

# Lightdash
[mcp_servers.lightdash-docs]
url = "https://docs.lightdash.com/mcp"

# Google Cloud
[mcp_servers.google_developer_knowledge]
url = "https://developerknowledge.googleapis.com/mcp"

[mcp_servers.google_developer_knowledge.env_http_headers]
X-Goog-Api-Key = "GOOGLE_DEVELOPER_KNOWLEDGE_API_KEY"

# Terraform
[mcp_servers.terraform]
command = "docker"
args = ["run", "-i", "--rm", "hashicorp/terraform-mcp-server"]

[projects."/Users/goodbyegangster/Documents/ChatGPT/mac new commer"]
trust_level = "trusted"

[projects."/Users/goodbyegangster/dotfiles"]
trust_level = "trusted"

[tui]
screen_reader_detection_done = true

[tui.model_availability_nux]
"gpt-6.1-sol" = 1
