line-length = 100

[lint]
select = ["ALL"]

ignore = [
  "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
  "BLE001", # Do not catch blind exception: `Exception`
  "COM812", # Trailing comma missing
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public module
  "D107", # Missing docstring in `__init__`
  "D202", # No blank lines allowed after function docstring
  "D203", # Checks for docstring on class definitions that are not preceded by a blank line.
  "D213", # Checks for docstring summary lines that are not positioned on the second physical line of the docstring.
  "D400", # First line should end with a period
  "D401", # First line should end with a period
  "D403", # First word of the docstring should be capitalized
  "D415", # First line should end with a period
  "EM101", # Exception must not use a string literal, assign to variable first
  "ERA001", # Found commented-out code
  "RUF001", # Checks for ambiguous Unicode characters in strings
  "RUF002", # Checks for ambiguous Unicode characters in docstring
  "RUF003", # Checks for ambiguous Unicode characters in comments
  "T201", # `print` found
  "TC001", # Move application import "" into a type-checking block
  "TC002", # Move application import "" into a type-checking block
  "TC003", # Move application import "" into a type-checking block
  "TRY003", # Avoid specifying long messages outside the exception class
]
